UMC5th-DrinkingGourmet/dg-FrontEnd

- .gitignore
- DrinkingGourmet.xcodeproj/project.pbxproj
- DrinkingGourmet/Source/Authentication/KakaoAuthViewModel.swift
- DrinkingGourmet/Source/Authentication/Viewcontroller/AuthenticationViewController.swift
- DrinkingGourmet/Source/Authentication/Viewcontroller/MemberInfoViewController.swift
- DrinkingGourmet/Source/Authentication/Viewcontroller/TermsViewController.swift
- DrinkingGourmet/Source/TodayCombination/Detail/View/TodayCombinationDetailView.swift
- DrinkingGourmet/Util/Extension/UIButton+Configuration.swift
[o] 기능 추가<br>
[] 기능 삭제<br>
[] 버그 수정<br>
<br>
ex) feat/social-login -> dev
<br>
- 카카오 로그인 사용자 정보를 화면에 보여주게끔 구현하였습니다.
- 약관 동의 화면 UI를 구현하였습니다
<br>
> feat: 카카오 로그인 사용자 정보 불러오기, 약관동의 화면 UI

- DrinkingGourmet/Source/TodayCombination/Detail/View/TodayCombinationDetailView.swift
- DrinkingGourmet/Source/TodayCombination/Detail/ViewController/TodayCombinationDetailViewController.swift
[o] 기능 추가<br>
[] 기능 삭제<br>
[] 버그 수정<br>
<br>
feat/today-combination-detail -> main
<br>
1. 댓글 아이콘 버튼 삭제
2. 댓글입력창 클릭 시 텍스트필드 가려지는 문제 해결
<br>
> Feat: 오늘의 조합 상세보기 UI 최종 구현

- DrinkingGourmet.xcodeproj/project.pbxproj
- DrinkingGourmet/Source/TodayCombination/Detail/View/TodayCombinationDetailView.swift
[] 기능 추가<br>
[] 기능 삭제<br>
[o] 버그 수정<br>
<br>
feat/restore-project-pbxproj -> main
<br>
project-pbxproj 파일이 변경됐는데 push를 안해줘서 에러가 나서 수정합니다.
<br>
> Fix: project-pbxproj 수정

- DrinkingGourmet.xcodeproj/project.pbxproj
- DrinkingGourmet/.gitignore
- DrinkingGourmet/App/AppDelegate.swift
- DrinkingGourmet/App/SceneDelegate.swift
- DrinkingGourmet/Info.plist
- DrinkingGourmet/Resource/Assets.xcassets/Colors/CheckmarkGray.colorset/Contents.json
- DrinkingGourmet/Source/Authentication/KakaoAuthViewModel.swift
- DrinkingGourmet/Source/Authentication/Viewcontroller/AuthenticationViewController.swift
- DrinkingGourmet/Source/Authentication/Viewcontroller/TermsViewController.swift
- DrinkingGourmet/Source/Upload/UploadedImgCollectionViewCell.swift
- DrinkingGourmet/Source/Upload/ViewController/UploadViewController.swift
- DrinkingGourmet/Util/Extension/UIColor+CustomColor.swift
[o] 기능 추가<br>
[] 기능 삭제<br>
[] 버그 수정<br>
<br>
ex) feat/upload-> main
<br>
사진 업로드 구현했습니다. 여러 화면에서 재사용할 수 있게끔 빠르게 리팩토링 후 다시 올리겠습니다.
<br>
https://github.com/UMC5th-DrinkingGourmet/dg-FrontEnd/assets/80039139/d96aedc8-72fb-4b4c-8e4a-655235164015
> feat: 사진 업로드 구현

- DrinkingGourmet.xcodeproj/project.pbxproj
- DrinkingGourmet/Source/Community/Home/ViewController/CommunityHomeVC.swift
- DrinkingGourmet/Source/RecipeBook/Detail/View/RecipeBookDetailCell.swift
- DrinkingGourmet/Source/RecipeBook/Detail/View/RecipeBookDetailInfoView.swift
- DrinkingGourmet/Source/RecipeBook/Detail/View/RecipeBookDetailView.swift
- DrinkingGourmet/Source/RecipeBook/Detail/ViewController/RecipeBookDetailVC.swift
- DrinkingGourmet/Source/RecipeBook/Home/View/RecipeBookHomeCell.swift
- DrinkingGourmet/Source/RecipeBook/Home/View/RecipeBookHomeView.swift
- DrinkingGourmet/Source/RecipeBook/Home/ViewController/RecipeBookHomeVC.swift
[O] 기능 추가<br>
[] 기능 삭제<br>
[] 버그 수정<br>
<br>
ex) feat/community -> main
<br>
1. 음주미식회 레시피북 UI 구현
2. 음주미식회 레시피북 상세보기 UI 구현
3. 커뮤니티 홈화면에서 이동 구현
<br>
> Feat: 음주미식회 레시피북 UI 구현

- DrinkingGourmet.xcodeproj/project.pbxproj
- DrinkingGourmet/App/SceneDelegate.swift
- DrinkingGourmet/Info.plist
- DrinkingGourmet/Source/MainMenu/ViewController/MainMenuViewController.swift
- DrinkingGourmet/Source/UserAuthentication/KakaoAuthViewModel.swift
- DrinkingGourmet/Source/UserAuthentication/UserDefaultManager.swift
- DrinkingGourmet/Source/UserAuthentication/Viewcontroller/AuthenticationViewController.swift
- DrinkingGourmet/Source/UserAuthentication/Viewcontroller/ProfileCreationViewController.swift
- DrinkingGourmet/Source/UserAuthentication/Viewcontroller/TermsViewController.swift
- DrinkingGourmet/Util/Extension/UIButton+Configuration.swift
- DrinkingGourmet/Util/InputTextField/InputTextFieldView.swift
[o] 기능 추가<br>
[] 기능 삭제<br>
[] 버그 수정<br>
<br>
feat/social-login -> main
<br>
- 시작 화면, 약관 동의 화면, 개인정보 입력 화면, 홈 화면 연결
- 개인 정보 입력 화면 구현
* 닉네임 유효성 검사(중복 검사는 아직 적용되지 않았고 길이, 특수문자 등을 처리)
* 성별 버튼 이벤트 처리
* 성별, 닉네임 조건 모두 충족시 화면 이동하도록 구현
- 유저 정보를 개인정보 입력 화면에 반영
<br>
> feat: 로그인 화면 연결, 사용자 정보 반영

- DrinkingGourmet.xcodeproj/project.pbxproj
- DrinkingGourmet/DrinkingGourmet.entitlements
[] 기능 추가<br>
[] 기능 삭제<br>
[] 버그 수정<br>
[o] 의존성, 환경 변수, 빌드 관련 코드 업데이트
<br>
feat/social-login -> main
<br>
bundle identifier 수정하였습니다.
<br>
> fix: bundle identifier 수정

- DrinkingGourmet/Source/Community/Home/View/CommunityHomeView.swift
- DrinkingGourmet/Source/Community/Home/ViewController/CommunityHomeVC.swift
[] 기능 추가<br>
[O] 기능 삭제<br>
[] 버그 수정<br>
<br>
feat/community-home -> main
<br>
1. 커뮤니티 홈 서치바 삭제
<br>
> Feat: 커뮤니티 홈 서치바 삭제

- DrinkingGourmet.xcodeproj/project.pbxproj
- DrinkingGourmet/Source/TodayCombination/Home/CombinationHomeDataManager.swift
- DrinkingGourmet/Source/TodayCombination/Home/CombinationHomeInput.swift
- DrinkingGourmet/Source/TodayCombination/Home/CombinationHomeModel.swift
- DrinkingGourmet/Source/TodayCombination/Home/View/TodayCombinationCell.swift
- DrinkingGourmet/Source/TodayCombination/Home/View/TodayCombinationView.swift
- DrinkingGourmet/Source/TodayCombination/Home/ViewController/TodayCombinationViewController.swift
[O] 기능 추가<br>
[] 기능 삭제<br>
[] 버그 수정<br>
<br>
feat/today-combination -> main
<br>
1. 플로팅 버튼 기능 축소
2. 오늘의 조합 홈 화면 API 연동
3. 페이징 처리
<br>
https://github.com/UMC5th-DrinkingGourmet/dg-FrontEnd/assets/147085742/b2c04bcd-bef2-45c9-ae9a-739d88ab2e90
<br>
1. 아직 헤더는 추가 X
2. 좋아요 API가 아직 나오지 않아 보류
> Feat: 오늘의조합 홈 API 연동

- DrinkingGourmet.xcodeproj/project.pbxproj
- DrinkingGourmet/Source/TodayCombination/Home/CombinationHomeDataManager.swift
- DrinkingGourmet/Source/TodayCombination/Home/CombinationHomeInput.swift
- DrinkingGourmet/Source/TodayCombination/Home/CombinationHomeModel.swift
- DrinkingGourmet/Source/TodayCombination/Home/ViewController/CombinationSearchVC.swift
- DrinkingGourmet/Source/TodayCombination/Home/ViewController/TodayCombinationViewController.swift
[O] 기능 추가<br>
[] 기능 삭제<br>
[] 버그 수정<br>
<br>
feat/today-combination -> main
<br>
1. 오늘의조합 검색 API 연동
2. 페이징 처리
<br>
https://github.com/UMC5th-DrinkingGourmet/dg-FrontEnd/assets/147085742/dc01413f-0c0a-457a-86f2-0dd6d639b3e5
1. 최근검색어 코어데이터 구현 (시간이 걸릴듯하네요,,)
2. 데이터 더 만들어서 페이징 처리 제대로 됐는지 확인하기
> Feat: 오늘의조합 검색 API 연동

- DrinkingGourmet.xcodeproj/project.pbxproj
- DrinkingGourmet/Source/Community/Home/ViewController/WeeklyBestCell.swift
- DrinkingGourmet/Source/WeeklyBest/Model/WeeklyBestDataManager.swift
- DrinkingGourmet/Source/WeeklyBest/Model/WeeklyBestInput.swift
- DrinkingGourmet/Source/WeeklyBest/Model/WeeklyBestModel.swift
- DrinkingGourmet/Source/WeeklyBest/ViewController/WeeklyBestSearchVC.swift
- DrinkingGourmet/Source/WeeklyBest/ViewController/WeeklyBestVC.swift
[O] 기능 추가<br>
[] 기능 삭제<br>
[] 버그 수정<br>
<br>
feat/wwekly-best -> main
<br>
1. 주간 베스트 조합 API 연동
2. revert한거 라이브러리 오류나서 삭제하고 다시 받았는데 버전 몇 개 바뀐거 같은데 확인부탁드립니다 ㅠㅠ
<br>
> Feat: 주간 베스트 조합 API 연동

- DrinkingGourmet/App/SceneDelegate.swift
- DrinkingGourmet/Source/Upload/ViewController/UploadViewController.swift
[] 기능 추가<br>
[] 기능 삭제<br>
[O] 버그 수정<br>
<br>
feat/upload-images -> main
<br>
- 이미지 저장하는 자료형 변경. CollectionView에서 사용시 다음 코드를 참고하여서 적용하면 될 것 같습니다.
if let imageList = imageList, !imageList.isEmpty {
imageView.image = imageList[0]
}
<br>
> fix: 이미지 저장 방법 변경

- DrinkingGourmet.xcodeproj/project.pbxproj
- DrinkingGourmet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- DrinkingGourmet/Source/Like/Model/LikeAllCombinationModel.swift
- DrinkingGourmet/Source/Like/Model/LikeAllRecipeBookModel.swift
- DrinkingGourmet/Source/Like/Model/LikeDataManager.swift
- DrinkingGourmet/Source/Like/Model/LikeInput.swift
- DrinkingGourmet/Source/Like/View/LikeCell.swift
- DrinkingGourmet/Source/Like/View/LikeView.swift
- DrinkingGourmet/Source/Like/ViewController/LikeViewController.swift
[O] 기능 추가<br>
[] 기능 삭제<br>
[] 버그 수정<br>
<br>
feat/like -> main
<br>
1. 좋아요 뷰 좋아요 한 오늘의 조합 조회 API 연동
<br>
https://github.com/UMC5th-DrinkingGourmet/dg-FrontEnd/assets/147085742/408a1f0e-866c-45e4-a6f1-b284bd904bd6
1. 페이징 처리 문제있어서 프론트 측에 수정 요청했습니다. ( 페이징 처리 전 코드입니다. )
2. 좋아요 삭제해도 반영이 안되서 프론트 측에 수정 요청했습니다.
3. 아직 레시피북 API연동이 되지않아 오늘의 조합만 해놨습니다.
> Feat: 좋아요 뷰 좋아요 한 오늘의 조합 조회 API 연동

- DrinkingGourmet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- DrinkingGourmet/Source/RecipeBook/Home/Model/RecipeBookHomeDataManager.swift
- DrinkingGourmet/Source/RecipeBook/Home/Model/RecipeBookHomeInput.swift
- DrinkingGourmet/Source/RecipeBook/Home/Model/RecipeBookHomeModel.swift
- DrinkingGourmet/Source/RecipeBook/Home/ViewController/RecipeBookHomeVC.swift
- DrinkingGourmet/Source/RecipeBook/Home/ViewController/RecipeBookSearchVC.swift
[O] 기능 추가<br>
[] 기능 삭제<br>
[] 버그 수정<br>
<br>
<br>
1. 레시피북 홈 Keychain 액세스 토큰 헤더로 수정
2. 레시피북 홈 페이징 처리
3. 서버에서 API 수정해서 관련 모델 수정
<br>
https://github.com/UMC5th-DrinkingGourmet/dg-FrontEnd/assets/147085742/49c9203a-0410-4245-b807-9c21350e2f13
> Refactor: 레시피북 홈 리펙토링 및 페이징 처리

- DrinkingGourmet/Source/TodayCombination/Home/ViewController/TodayCombinationViewController.swift
[] 기능 추가<br>
[] 기능 삭제<br>
[] 버그 수정<br>
<br>
feat/today-combination -> dev
<br>
1. 오늘의 조합 홈 페이징 처리 리펙토링
<br>
https://github.com/UMC5th-DrinkingGourmet/dg-FrontEnd/assets/147085742/604ee07b-9660-4bb6-9a4d-712d0adfa5c1
> Refactor: 오늘의 조합 홈 페이징 처리 리펙토링

- DrinkingGourmet/Source/TodayCombination/Detail/Model/CombinationCommentModel.swift
- DrinkingGourmet/Source/TodayCombination/Detail/Model/CombinationDetailDataManager.swift
- DrinkingGourmet/Source/TodayCombination/Detail/Model/CombinationDetailModel.swift
- DrinkingGourmet/Source/TodayCombination/Detail/View/Comments/CommentsView.swift
- DrinkingGourmet/Source/TodayCombination/Detail/View/TodayCombinationDetailView.swift
- DrinkingGourmet/Source/TodayCombination/Detail/ViewController/TodayCombinationDetailViewController.swift
[] 기능 추가<br>
[] 기능 삭제<br>
[] 버그 수정<br>
<br>
feat/today-combination -> main
<br>
1.  오늘의 조합 API 변경요청 반영되서 모델 수정 및 리펙토링했습니다.
<br>
> Refactor: 오늘의 조합 API 수정 후 모델 수정 및 리펙토링

- DrinkingGourmet/Source/TodayCombination/Detail/Model/CombinationDetailDataManager.swift
- DrinkingGourmet/Source/TodayCombination/Detail/View/Comments/CommentView.swift
- DrinkingGourmet/Source/TodayCombination/Detail/View/Comments/CommentsView.swift
- DrinkingGourmet/Source/TodayCombination/Detail/ViewController/TodayCombinationDetailViewController.swift
- DrinkingGourmet/Source/TodayCombination/Home/Model/CombinationHomeModel.swift
- DrinkingGourmet/Source/TodayCombination/Home/View/TodayCombinationCell.swift
- DrinkingGourmet/Source/TodayCombination/Home/ViewController/TodayCombinationViewController.swift
[O] 기능 추가<br>
[] 기능 삭제<br>
[] 버그 수정<br>
<br>
feat/today-combination -> main
<br>
1. 대댓글 삭제에 따른 답글쓰기 버튼, 답글갯수 라벨 삭제 후 높이 조정
2. 오늘의 조합 홈 화면에서 좋아요 한 글만 하트 아이콘 보이게
3. 오늘의 조합 좋아요 API 연동
<br>
> Feat: 댓글 UI 수정 및 오늘의 조합 좋아요 관련 UI 수정, API 연동

- DrinkingGourmet/Source/RecipeBook/Home/Model/RecipeBookHomeModel.swift
- DrinkingGourmet/Source/RecipeBook/Home/View/RecipeBookHomeCell.swift
- DrinkingGourmet/Source/RecipeBook/Home/ViewController/RecipeBookHomeVC.swift
[] 기능 추가<br>
[] 기능 삭제<br>
[O] 버그 수정<br>
<br>
feat/recipe-book -> main
<br>
1. API 수정되서 레시피북 홈 조회 모델수정
2. 페이징 버그 수정
3. 내가 좋아요 한 글만 하트 아이콘 표시
<br>
> Refactor: 레시피북 홈 조회 모델수정 및 페이징 버그 수정

- DrinkingGourmet.xcodeproj/project.pbxproj
- DrinkingGourmet/Source/Mypage/Model/MyPageCombinationModel.swift
- DrinkingGourmet/Source/Mypage/Model/MyPageDataManager.swift
- DrinkingGourmet/Source/Mypage/Model/MyPageInput.swift
- DrinkingGourmet/Source/Mypage/Model/MyPageRecipeBookModel.swift
- DrinkingGourmet/Source/Mypage/Model/MyPageRecommendModel.swift
- DrinkingGourmet/Source/Mypage/Model/MyPageUserModel.swift
- DrinkingGourmet/Source/Mypage/View/MyPageLowerView.swift
- DrinkingGourmet/Source/Mypage/View/MyPageView.swift
- DrinkingGourmet/Source/Mypage/ViewController/MyPageViewController.swift
[O] 기능 추가<br>
[] 기능 삭제<br>
[] 버그 수정<br>
<br>
<br>
1. 마이페이지 API연동
<br>
https://github.com/UMC5th-DrinkingGourmet/dg-FrontEnd/assets/147085742/071e9e12-aea3-407a-9351-0d2ce3b625c8
1. 페이징 계속 안하고 있는데 나중에 할 수 있겠죠 ,,
> Feat: 마이페이지 API연동 페이징 전

- DrinkingGourmet.xcodeproj/project.pbxproj
- DrinkingGourmet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- DrinkingGourmet.xcodeproj/xcuserdata/hwijinjeong.xcuserdatad/xcschemes/xcschememanagement.plist
- DrinkingGourmet/App/SceneDelegate.swift
- DrinkingGourmet/Source/RecipeBook/Home/ViewController/RecipeBookHomeVC.swift
- DrinkingGourmet/Source/TodayCombination/Upload/Model/CombinationUploadDataManager.swift
- DrinkingGourmet/Source/TodayCombination/Upload/Model/CombinationUploadModel.swift
- DrinkingGourmet/Source/TodayCombination/Upload/ViewController/CombinationUploadVC.swift
- DrinkingGourmet/Source/Upload/ViewController/UploadViewController.swift
- DrinkingGourmet/Util/Extension/UITextField+setPlaceholder.swift
- DrinkingGourmet/Util/InputTextField/InputTextFieldView.swift
[o] 기능 추가<br>
[] 기능 삭제<br>
[] 버그 수정<br>
<br>
feat/community-upload -> main
<br>
커뮤니티 업로드 구현하였습니다.
<br>
> feat: 오늘의 조합 업로드 구현

- DrinkingGourmet.xcodeproj/project.pbxproj
- DrinkingGourmet/Source/RecipeBook/Home/ViewController/RecipeBookHomeVC.swift
- DrinkingGourmet/Source/RecipeBook/Upload/Model/RecipeBookUploadDataManager.swift
- DrinkingGourmet/Source/RecipeBook/Upload/Model/RecipeBookUpoadModel.swift
- DrinkingGourmet/Source/RecipeBook/Upload/ViewController/RecipeBookUploadViewController.swift
[o] 기능 추가<br>
[] 기능 삭제<br>
[] 버그 수정<br>
<br>
feat/community-upload -> main
<br>
레시피북 업로드 구현하였습니다
<br>
> feat: 레시피북 업로드 구현

- DrinkingGourmet/Source/RecipeBook/Detail/ViewController/RecipeBookDetailVC.swift
- DrinkingGourmet/Source/TodayCombination/Detail/ViewController/TodayCombinationDetailViewController.swift
[] 기능 추가<br>
[] 기능 삭제<br>
[] 버그 수정<br>
<br>
<br>
<br>
> Fix: 레시피북, 조합 찐최종

- DrinkingGourmet/App/SceneDelegate.swift
- DrinkingGourmet/Source/RecipeBook/Upload/Model/RecipeBookUploadDataManager.swift
- DrinkingGourmet/Source/RecipeBook/Upload/Model/RecipeBookUpoadModel.swift
- DrinkingGourmet/Source/RecipeBook/Upload/ViewController/RecipeBookUploadViewController.swift
- DrinkingGourmet/Source/TodayCombination/Upload/ViewController/CombinationUploadVC.swift
[] 기능 추가<br>
[] 기능 삭제<br>
[o] 버그 수정<br>
<br>
feat/community -> main
<br>
레시피북 네트워킹 버그 수정하였습니다.
오늘의 조합, 레시피북 둘 다 textfield 효과, 글자수 제한 등 수정하였습니다
<br>
> fix: 레시피북 네트워킹, UI 버그 수정

- DrinkingGourmet/Source/Like/ViewController/LikeViewController.swift
[] 기능 추가<br>
[O] 기능 삭제<br>
[] 버그 수정<br>
<br>
<br>
<br>
> Fix: 좋아요 페이지 페이징 관련 코드 삭제

- DrinkingGourmet/Source/Community/Home/ViewController/WeeklyBestCell.swift
- DrinkingGourmet/Source/WeeklyBest/Model/WeeklyBestDataManager.swift
- DrinkingGourmet/Source/WeeklyBest/ViewController/WeeklyBestVC.swift
[] 기능 추가<br>
[] 기능 삭제<br>
[] 버그 수정<br>
<br>
<br>
<br>
> Fix: 주간베스트 코드 수정

- DrinkingGourmet/Source/TodayCombination/Home/Model/CombinationHomeModel.swift
- DrinkingGourmet/Source/TodayCombination/Home/ViewController/TodayCombinationViewController.swift
[] 기능 추가<br>
[] 기능 삭제<br>
[] 버그 수정<br>
<br>
<br>
<br>
> Fix: 오늘의 조합 홈화면 이미지 nil값 방지

- DrinkingGourmet/App/SceneDelegate.swift
- DrinkingGourmet/Source/Like/Model/LikeAllCombinationModel.swift
- DrinkingGourmet/Source/Like/Model/LikeAllRecipeBookModel.swift
- DrinkingGourmet/Source/Like/ViewController/LikeViewController.swift
- DrinkingGourmet/Source/MainMenu/ViewController/MainMenuViewController.swift
- DrinkingGourmet/Source/Mypage/ViewController/MyPageViewController.swift
- DrinkingGourmet/Source/Recommend/MyRecommend/ViewController/GetDrinkingRecommendViewController.swift
- DrinkingGourmet/Source/Recommend/MyRecommend/ViewController/MyDrinkStyleViewController.swift
- DrinkingGourmet/Source/TabBar/Viewcontroller/TabBarViewController.swift
[O] 기능 추가<br>
[] 기능 삭제<br>
[] 버그 수정<br>
<br>
<br>
<br>
> Feat: 탭바 설정

- DrinkingGourmet/Source/MainMenu/ViewController/MainMenuViewController.swift
[O] 기능 추가<br>
[] 기능 삭제<br>
[] 버그 수정<br>
<br>
<br>
1. 방금 올렸던거 커밋도 안하고 올렸네요. 찐찐 최종입니다.
<br>
> Feat: 탭바 찐찐최종

- .github/ISSUE_TEMPLATE/feature_request.md
[] 기능 추가<br>
[] 기능 삭제<br>
[] 버그 수정<br>
<br>
<br>
<br>
> Docs: 이슈 템플릿 변경

- DrinkingGourmet.xcodeproj/project.pbxproj
- DrinkingGourmet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- DrinkingGourmet/Source/TodayCombination/Home/View/TodayCombinationCell.swift
- DrinkingGourmet/Source/TodayCombination/Home/View/TodayCombinationView.swift
- DrinkingGourmet/Source/TodayCombination/Home/ViewController/CombinationSearchVC.swift
- DrinkingGourmet/Source/TodayCombination/Home/ViewController/TodayCombinationViewController.swift
resolve #84 
오늘의 조합 홈 새로고침 구현
viewWillAppear 관련 코드 삭제 후 새로고침 구현했습니다.
상세보기에서 좋아요/댓글 수가 변경되고 뒤로가기 하면 실시간으로 변경되는 것은 아직 구현 못했습니다.
> [#84] Feat: 오늘의 조합 홈 새로고침 구현

- DrinkingGourmet/Source/Community/Home/ViewController/WeeklyBestCell.swift
- DrinkingGourmet/Source/Community/Home/ViewController/WeeklyBestView.swift
- DrinkingGourmet/Source/RecipeBook/Home/View/RecipeBookHomeCell.swift
- DrinkingGourmet/Source/RecipeBook/Home/View/RecipeBookHomeView.swift
- DrinkingGourmet/Source/RecipeBook/Home/ViewController/RecipeBookHomeVC.swift
- DrinkingGourmet/Source/WeeklyBest/ViewController/WeeklyBestVC.swift
resolve #88 
- 주간 베스트 조합 새로고침 구현
- 레시피북 새로고침 구현
- 주간 베스트 조합 페이징 기능 리펙토링
> [#88] Feat: 커뮤니티 새로고침 구현 및 페이징 기능 리펙토링

- DrinkingGourmet.xcodeproj/project.pbxproj
- DrinkingGourmet/Source/Community/Home/View/CommunityView.swift
- DrinkingGourmet/Source/Community/Home/ViewController/CommunityViewController.swift
- DrinkingGourmet/Source/Community/Home/ViewController/WeeklyBestView.swift
- DrinkingGourmet/Source/Community/Search/View/CustomSearchBar.swift
- DrinkingGourmet/Source/RecipeBook/Home/View/RecipeBookHomeView.swift
- DrinkingGourmet/Source/RecipeBook/Home/ViewController/RecipeBookHomeVC.swift
- DrinkingGourmet/Source/TabBar/Viewcontroller/TabBarViewController.swift
- DrinkingGourmet/Source/TodayCombination/Home/View/TodayCombinationView.swift
- DrinkingGourmet/Source/TodayCombination/Home/ViewController/TodayCombinationViewController.swift
- DrinkingGourmet/Source/WeeklyBest/ViewController/WeeklyBestVC.swift
resolve #94 
검색창을 텍스트필드에서 버튼으로 변경했습니다. (오늘의 조합, 주간 베스트조합, 레시피북)
> [#94] Design: 커뮤니티 검색창 버튼으로 변경

- DrinkingGourmet.xcodeproj/project.pbxproj
- DrinkingGourmet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- DrinkingGourmet/Source/RecipeBook/Detail/ViewController/RecipeBookDetailVC.swift
- DrinkingGourmet/Source/RecipeBook/Home/Model/RecipeBookHomeModel.swift
- DrinkingGourmet/Source/RecipeBook/Home/ViewController/RecipeBookHomeVC.swift
- DrinkingGourmet/Source/TodayCombination/Detail/ViewController/TodayCombinationDetailViewController.swift
- DrinkingGourmet/Source/TodayCombination/Home/Model/CombinationHomeModel.swift
- DrinkingGourmet/Source/TodayCombination/Home/ViewController/TodayCombinationViewController.swift
- DrinkingGourmet/Source/WeeklyBest/Model/WeeklyBestModel.swift
- DrinkingGourmet/Source/WeeklyBest/ViewController/WeeklyBestVC.swift
resolve #93 
커뮤니티 글 상세보기에서 홈으로 좋아요 아이콘 반영 구현
https://github.com/UMC5th-DrinkingGourmet/dg-FrontEnd/assets/147085742/48f7c696-0bad-4a96-a3d3-b7d6d487c340
댓글 수랑 좋아요 수 반영은 아직 못했습니다,,
> [#93] Feat: 커뮤니티 글 상세보기에서 홈으로 좋아요 아이콘 반영 구현

- DrinkingGourmet/Source/Community/Search/View/CustomResultSearchBar.swift
- DrinkingGourmet/Source/Community/Search/View/SearchResultView.swift
- DrinkingGourmet/Source/RecipeBook/Home/Model/RecipeBookHomeDataManager.swift
- DrinkingGourmet/Source/RecipeBook/Home/ViewController/RecipeBookHomeVC.swift
- DrinkingGourmet/Source/RecipeBook/Home/ViewController/RecipeBookSearchVC.swift
- DrinkingGourmet/Source/TodayCombination/Home/Model/CombinationHomeDataManager.swift
- DrinkingGourmet/Source/TodayCombination/Home/ViewController/CombinationSearchVC.swift
- DrinkingGourmet/Source/TodayCombination/Home/ViewController/TodayCombinationViewController.swift
- DrinkingGourmet/Source/WeeklyBest/Model/WeeklyBestDataManager.swift
- DrinkingGourmet/Source/WeeklyBest/Model/WeeklyBestInput.swift
- DrinkingGourmet/Source/WeeklyBest/ViewController/WeeklyBestSearchVC.swift
- DrinkingGourmet/Source/WeeklyBest/ViewController/WeeklyBestVC.swift
resolve #97 
- 오늘의 조합 검색기능 구현
- 주간 베스트 조합 검색기능 구현
- 레시피북 검색기능 구현
https://github.com/UMC5th-DrinkingGourmet/dg-FrontEnd/assets/147085742/f7f66036-1f4d-4f17-a5cf-60fb46784468
최근검색어 구현은 아직 못했습니다.
서버를 통해서 할지 정해야 할 것 같습니다.
> [#97] Feat: 커뮤니티 검색기능 구현

- DrinkingGourmet/Info.plist
- DrinkingGourmet/Source/Report/ViewController/ReportViewController.swift
> [#107] Feat: 레시피북 댓글 신고 구현

- DrinkingGourmet.xcodeproj/project.pbxproj
- DrinkingGourmet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- DrinkingGourmet/Source/Like/ViewController/LikeViewController.swift
- DrinkingGourmet/Source/Report/View/ReportCompletePopUpView.swift
- DrinkingGourmet/Source/Report/View/ReportView.swift
- DrinkingGourmet/Source/Report/ViewController/ReportViewController.swift
resolve #117 
- 신고완료 토스트뷰 (라이브러리 설치)
- 신고 뷰컨 리펙토링
- 좋아요 탭에서 게시물 신고했을 때 pop 구현
https://github.com/UMC5th-DrinkingGourmet/dg-FrontEnd/assets/147085742/db5fa3f6-6e94-4a0f-8b78-afcb765b3adc
토스트뷰 라이브러리 https://github.com/scalessec/Toast-Swift 사용했습니다.
> [#117] Feat: 토스트뷰 구현 및 리펙토링

- DrinkingGourmet.xcodeproj/project.pbxproj
- DrinkingGourmet/App/SceneDelegate.swift
- DrinkingGourmet/Info.plist
- DrinkingGourmet/Source/UserAuthentication/AppleAuthViewModel.swift
- DrinkingGourmet/Source/UserAuthentication/Model/UserInfoDataManager.swift
- DrinkingGourmet/Source/UserAuthentication/Viewcontroller/AuthenticationViewController.swift
- DrinkingGourmet/Source/UserAuthentication/Viewcontroller/ProfileCreationViewController.swift
resolve #
Apple 소셜 로그인 기능을 추가하였습니다.
> [#120] 애플 소셜 로그인 구현

- DrinkingGourmet.xcodeproj/project.pbxproj
- DrinkingGourmet/App/SceneDelegate.swift
- DrinkingGourmet/Source/Setting/Home/ViewController/SettingViewController.swift
- DrinkingGourmet/Source/Setting/Question/View/AnswerView.swift
- DrinkingGourmet/Source/Setting/Question/View/DeleteAccountView.swift
- DrinkingGourmet/Source/Setting/Question/View/QuestionCell.swift
- DrinkingGourmet/Source/Setting/Question/View/QuestionView.swift
- DrinkingGourmet/Source/Setting/Question/ViewController/AnswerViewController.swift
- DrinkingGourmet/Source/Setting/Question/ViewController/DeleteAccountViewController.swift
- DrinkingGourmet/Source/Setting/Question/ViewController/QuestionViewController.swift
resolve #92 
자주 묻는 질문 UI 구현
https://github.com/UMC5th-DrinkingGourmet/dg-FrontEnd/assets/147085742/5669552a-a67d-4e96-bbc5-adcc6b9abec2
나중에 회원탈퇴 API 연결해야합니다
> [#92] Feat: 자주 묻는 질문 UI 구현

- DrinkingGourmet.xcodeproj/project.pbxproj
- DrinkingGourmet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- DrinkingGourmet/Source/Like/View/LikeView.swift
- DrinkingGourmet/Source/Like/ViewController/LikeCombinationViewController.swift
- DrinkingGourmet/Source/Like/ViewController/LikeRecipeBookViewController.swift
- DrinkingGourmet/Source/Like/ViewController/LikeTapmanViewController.swift
- DrinkingGourmet/Source/Report/ViewController/ReportViewController.swift
- DrinkingGourmet/Source/TabBar/Viewcontroller/TabBarViewController.swift
resolve #128 
Tapman 라이브러리 사용해서 좋아요 페이지 리펙토링
https://github.com/UMC5th-DrinkingGourmet/dg-FrontEnd/assets/147085742/b1f4b08e-3c49-49ad-aaf3-916bc433f603
스크롤 문제 해결완료
> [#128] Refactor: 좋아요 페이지 리펙토링

- DrinkingGourmet.xcodeproj/project.pbxproj
- DrinkingGourmet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- DrinkingGourmet/Source/Setting/Home/ViewController/SettingViewController.swift
- DrinkingGourmet/Source/Setting/Question/ViewController/AnswerViewController.swift
- DrinkingGourmet/Source/Setting/TermsAndPolicies/TermsAndPoliciesViewController.swift
resolve #131 
https://github.com/UMC5th-DrinkingGourmet/dg-FrontEnd/assets/147085742/aaaa2697-bacd-4ca0-8e43-e31b56c7d02f
자주 묻는 질문 QuestionCell, AnswerViewController 재사용
> [#131] Feat: 마이페이지 약관 및 정책 구현

- DrinkingGourmet/Source/Setting/Home/View/SettingCell.swift
- DrinkingGourmet/Source/Setting/Home/ViewController/SettingViewController.swift
resolve #133 
- 섹션0(지원 및 정보) 아이콘 삽입
- 회원탈퇴 textColor .red로 변경
> [#133] Design: 마이페이지 Cell 디자인 수정

- DrinkingGourmet/Source/Combination/Detail/ViewController/CombinationDetailViewController.swift
- DrinkingGourmet/Source/Combination/RemovedAlertView.swift
- DrinkingGourmet/Source/RecipeBook/Detail/ViewController/RecipeBookDetailViewController.swift
- DrinkingGourmet/Source/Report/View/ReportView.swift
- DrinkingGourmet/Source/Report/ViewController/ReportViewController.swift
- DrinkingGourmet/Source/Service/AdministrationService.swift
- DrinkingGourmet/Source/Setting/Home/View/SettingCell.swift
- DrinkingGourmet/Source/Setting/Home/ViewController/SettingViewController.swift
resolve #135 
- 신고하기 API 수정 (reportedMemberId 리퀘스트 파라미터 추가)
> [#135] Fix: 신고하기 API 수정

- DrinkingGourmet/Source/Combination/Detail/ViewController/CombinationDetailViewController.swift
- DrinkingGourmet/Source/Like/ViewController/LikeCombinationViewController.swift
- DrinkingGourmet/Source/Like/ViewController/LikeRecipeBookViewController.swift
- DrinkingGourmet/Source/Like/ViewController/LikeTapmanViewController.swift
- DrinkingGourmet/Source/RecipeBook/Detail/ViewController/RecipeBookDetailViewController.swift
- DrinkingGourmet/Source/Report/View/ReportCompletePopUpView.swift
resolve #137 
- 조합 / 레시피북 게시물 버튼으로 차단했을 때
- 조합 / 레시피북 댓글 버튼으로 차단했을 때
- 차단완료 토스트 메시지
https://github.com/user-attachments/assets/867fb946-449b-40d2-8c3a-1dff72daf3ae
https://github.com/user-attachments/assets/2502590e-b070-4564-ba84-e7ab64bc5893
> [#137] Feat: 차단 구현

- DrinkingGourmet/Source/MainMenu/ViewController/MainMenuViewController.swift
> [#146] 메인페이지 UI 컴포넌트 레이아웃 보완

- DrinkingGourmet/Source/Mypage/ViewController/MyPageViewController.swift
- DrinkingGourmet/Source/Service/MyPageService.swift
- DrinkingGourmet/Source/Setting/Home/View/SettingTopView.swift
- DrinkingGourmet/Source/Setting/Home/ViewController/SettingViewController.swift
- DrinkingGourmet/Source/UserAuthentication/Viewcontroller/ProfileCreationViewController.swift
resolve #145 
- 마이페이지 내 정보 수정 API 연결
- 설정 내 정보 수정 API 연결
https://github.com/user-attachments/assets/925f9aa5-aab5-4127-b75b-7735a59d688c
https://github.com/user-attachments/assets/52240888-83e2-4cd3-aab1-6e58077e2cce
> [#145] feat: 내 정보 수정 API 연결

- DrinkingGourmet/Source/MainMenu/ViewController/MainMenuViewController.swift
- DrinkingGourmet/Source/Upload/ViewController/UploadedImgCollectionViewCell.swift
- DrinkingGourmet/Source/UserAuthentication/Viewcontroller/AuthenticationViewController.swift
> [#152] 유저 구분 후 로그인 처리 로직 수정

- DrinkingGourmet/Source/UserAuthentication/Viewcontroller/ProfileCreationViewController.swift
- DrinkingGourmet/Util/InputTextField/InputTextFieldView.swift
> [#160] 프로필 입력 UX 개선

- DrinkingGourmet/Source/Combination/Detail/ViewController/CombinationDetailViewController.swift
- DrinkingGourmet/Source/Combination/Upload/ViewController/CombinationUploadVC.swift
- DrinkingGourmet/Source/Network/Service/CombinationService.swift
- DrinkingGourmet/Source/Network/Service/SignService.swift
- DrinkingGourmet/Source/RecipeBook/Detail/ViewController/RecipeBookDetailViewController.swift
- DrinkingGourmet/Source/RecipeBook/Upload/ViewController/RecipeBookUploadViewController.swift
- DrinkingGourmet/Source/Setting/Home/ViewController/SettingViewController.swift
- DrinkingGourmet/Source/UserAuthentication/Viewcontroller/AuthenticationViewController.swift
> [#144] feat: 오늘의 조합 게시글 수정 및 회원탈퇴 API 연결

- DrinkingGourmet/Source/Network/Service/RecipeBookService.swift
- DrinkingGourmet/Source/RecipeBook/Detail/ViewController/RecipeBookDetailViewController.swift
- DrinkingGourmet/Source/RecipeBook/Home/ViewController/RecipeBookHomeViewController.swift
- DrinkingGourmet/Source/RecipeBook/Upload/ViewController/RecipeBookUploadViewController.swift
> [#164] feat: 레시피북 게시글 수정 API 연결

- DrinkingGourmet/Source/UserAuthentication/Viewcontroller/ProfileCreationViewController.swift
- DrinkingGourmet/Util/Extension/UIButton+Configuration.swift
- DrinkingGourmet/Util/InputTextField/InputTextFieldView.swift
> [#162] 회원가입 시, 일부 정보 선택 입력으로 변경

- DrinkingGourmet/Source/UserAuthentication/Viewcontroller/TermsViewController.swift
> [#169] feat: 이용약관 API 연결

- DrinkingGourmet/App/SceneDelegate.swift
- DrinkingGourmet/Source/Network/Auth/AuthInterceptor.swift
resolve #172 
refreshToken 만료 시 키체인 토큰을 삭제하는 기능을 추가했습니다.
> [#172] refreshToken 만료 시 키체인 토큰 삭제 기능 추가

- DrinkingGourmet/App/SceneDelegate.swift
- DrinkingGourmet/Source/Network/Auth/AuthInterceptor.swift
- DrinkingGourmet/Source/UserAuthentication/Viewcontroller/ProfileCreationViewController.swift
> [#175] 사용자 정보 입력 시 UserDefaults에 저장 기능 추가

- DrinkingGourmet/Source/Network/DTOs/RecipeBookUploadDTO.swift
- DrinkingGourmet/Source/Network/Service/CombinationUpoadService.swift
- DrinkingGourmet/Source/Network/Service/RecipeBookService.swift
- DrinkingGourmet/Source/Network/Service/RecipeBookUploadService.swift
- DrinkingGourmet/Source/RecipeBook/Detail/ViewController/RecipeBookDetailViewController.swift
- DrinkingGourmet/Source/RecipeBook/Upload/ViewController/RecipeBookUploadViewController.swift
> [#171] feat: 레시피북 게시글 업로드 및 수정 구현

- DrinkingGourmet/Info.plist
- DrinkingGourmet/Source/UserAuthentication/Viewcontroller/TermsViewController.swift
resolve #179 
토큰이 없어서 post를 못하는데 싱글톤으로 이용약관 담아서 로그인 후 쏘는거 나중에 구현하겠습니다 ~
> [#179] feat: 약관 개수 변경 및 상세보기 구현

- DrinkingGourmet/Source/WeeklyBest/ViewController/WeeklyBestViewController.swift
> [#181] design: 주간 베스트 조합 업로드 버튼 삭제 함수 추가

- DrinkingGourmet/App/AppDelegate.swift
- DrinkingGourmet/App/Base.lproj/LaunchScreen.storyboard
- DrinkingGourmet/Source/UserAuthentication/Viewcontroller/AuthenticationViewController.swift
resolve #KAN-10
스플래시 화면을 추가했습니다.
> [KAN-10][add] 로그인 스플래시 추가

- DrinkingGourmet.xcodeproj/project.pbxproj
- DrinkingGourmet/App/AppDelegate.swift
- DrinkingGourmet/App/Base.lproj/LaunchScreen.storyboard
- DrinkingGourmet/App/SceneDelegate.swift
- DrinkingGourmet/Source/Network/Service/SignService.swift
- DrinkingGourmet/Source/UserAuthentication/TokenParser.swift
- DrinkingGourmet/Source/UserAuthentication/Viewcontroller/AuthenticationViewController.swift
- DrinkingGourmet/Source/UserAuthentication/Viewcontroller/ProfileCreationViewController.swift
- DrinkingGourmet/Source/UserAuthentication/Viewcontroller/TermsViewController.swift
- DrinkingGourmet/Util/InputTextField/InputTextFieldView.swift
resolve #
- 선택 사항 입력 예외처리 강화
- 20세부터 나이를 설정할 수 있도록 사용자 연령 범위 제한
> 회원가입 선택사항 입력 예외처리 및 회원정보 입력 시, 사용자 연령 범위 수정

- DrinkingGourmet.xcodeproj/project.pbxproj
- DrinkingGourmet/App/AppDelegate.swift
- DrinkingGourmet/App/Base.lproj/LaunchScreen.storyboard
- DrinkingGourmet/App/SceneDelegate.swift
- DrinkingGourmet/Source/MainMenu/ViewController/MainMenuViewController.swift
- DrinkingGourmet/Source/Network/DTOs/Response/CombinationResponseDTO.swift
- DrinkingGourmet/Source/Network/Service/MainMenuService.swift
- DrinkingGourmet/Source/Network/Service/SignService.swift
- DrinkingGourmet/Source/UserAuthentication/TokenParser.swift
- DrinkingGourmet/Source/UserAuthentication/Viewcontroller/AuthenticationViewController.swift
- DrinkingGourmet/Source/UserAuthentication/Viewcontroller/ProfileCreationViewController.swift
- DrinkingGourmet/Source/UserAuthentication/Viewcontroller/TermsViewController.swift
- DrinkingGourmet/Util/InputTextField/InputTextFieldView.swift
resolve #[KAN-12][feat] 메인페이지 새로고침 추가
메인페이지 새로고침 추가했습니다.
> [KAN-12][feat] 메인페이지 새로고침 추가

- DrinkingGourmet/Source/Combination/Detail/View/CombinationDetailHeaderView.swift
- DrinkingGourmet/Source/Combination/Detail/ViewController/CombinationDetailViewController.swift
- DrinkingGourmet/Source/Combination/Upload/ViewController/CombinationUploadVC.swift
- DrinkingGourmet/Source/Network/DTOs/CombinationDTO.swift
> [#183] refactor: 오늘의 조합 업로드 & 수정 리팩토링

- DrinkingGourmet/Source/Community/Search/View/SearchResultView.swift
- DrinkingGourmet/Source/MainMenu/ViewController/MainMenuViewController.swift
- DrinkingGourmet/Source/Recommend/MyDrinkingStyle/Controller/SelectAlcoholDegreeViewController.swift
- DrinkingGourmet/Source/Recommend/MyDrinkingStyle/Controller/SelectDrinkCapacityViewController.swift
- DrinkingGourmet/Source/Recommend/MyDrinkingStyle/Controller/SelectDrinkFrequencyViewController.swift
- DrinkingGourmet/Source/Recommend/MyDrinkingStyle/Controller/SelectTypeOfLiquorViewController.swift
- DrinkingGourmet/Source/Recommend/MyDrinkingStyle/Controller/WelcomeViewController.swift
- DrinkingGourmet/Source/Recommend/MyDrinkingStyle/Model/MyDrinkingStyleDataManager.swift
- DrinkingGourmet/Source/Setting/Home/ViewController/SettingViewController.swift
- DrinkingGourmet/Source/UserAuthentication/Viewcontroller/ProfileCreationViewController.swift
> [#191] feat: 주류 추천 기본 정보 수정 구현

- DrinkingGourmet/Source/Combination/Detail/View/CombinationDetailHeaderView.swift
- DrinkingGourmet/Source/Combination/Detail/ViewController/CombinationDetailViewController.swift
- DrinkingGourmet/Source/Combination/Upload/ViewController/CombinationUploadVC.swift
- DrinkingGourmet/Source/Community/Search/View/SearchResultView.swift
- DrinkingGourmet/Source/MainMenu/ViewController/MainMenuViewController.swift
- DrinkingGourmet/Source/Network/DTOs/CombinationDTO.swift
- DrinkingGourmet/Source/UserAuthentication/Viewcontroller/ProfileCreationViewController.swift
resolve #189 
메인화면 백버튼 숨기기, 최근검색어 Label 삭제도 했습니다~
> [#189] feat: 회원정보 수정하기 beforeData 세팅

- DrinkingGourmet/Source/Mypage/ViewController/MyPageViewController.swift
- DrinkingGourmet/Source/Recommend/RequestRecommend/ViewController/RecommendStartViewController.swift
- DrinkingGourmet/Source/Setting/Home/ViewController/SettingViewController.swift
> [#194] feat: 마이페이지 진입시 UserDefault 업데이트

- DrinkingGourmet/Source/Recommend/RequestRecommend/ViewController/RecommendStartViewController.swift
resolve #194 
코드 한줄을 빼먹어서 빠르게 머지될지 몰랐네요 ㅎㅎ
> [#194] feat: 주류추천 시작 시 UserDefaultManager 업데이트 추가

- DrinkingGourmet/Source/MainMenu/ViewController/MainMenuViewController.swift
resolve #KAN-14
resolve #KAN-15
> 메인페이지에서 게시글 클릭 시, 상세 페이지로 이동하는 기능 추가

- DrinkingGourmet/App/SceneDelegate.swift
- DrinkingGourmet/Source/Network/Service/SignService.swift
resolve #[KAN-27]
자동로그인 시, memberId 저장하는 로직을 추가했습니다.
> [KAN-27][feat] 자동로그인 시, memberId 저장 로직 추가

- DrinkingGourmet/Source/Combination/Upload/ViewController/CombinationUploadVC.swift
- DrinkingGourmet/Source/RecipeBook/Upload/ViewController/RecipeBookUploadViewController.swift
resolve #199 
> 확인 버튼 눌렀을 때
> 설정 들어갔지만 허용 안했을 때
> [#199] feat: 업로드 앨범 접근 거부 시 pop 구현

- DrinkingGourmet/Source/Mypage/View/MyPageView.swift
- DrinkingGourmet/Source/Mypage/ViewController/MyPageViewController.swift
- DrinkingGourmet/Source/Network/Service/MyPageService.swift
- DrinkingGourmet/Source/Setting/Home/View/SettingTopView.swift
- DrinkingGourmet/Source/Setting/Home/ViewController/SettingViewController.swift
- DrinkingGourmet/Source/UserAuthentication/Viewcontroller/ProfileCreationViewController.swift
- DrinkingGourmet/Source/UserAuthentication/Viewcontroller/TermsViewController.swift
resolve #206 
https://github.com/user-attachments/assets/148225ad-56dd-42d4-9a3d-7d1c12e85ea8
> [#206] feat: 프로필 사진 수정 구현

- DrinkingGourmet/Source/UserAuthentication/Viewcontroller/ProfileCreationViewController.swift
- DrinkingGourmet/Source/UserAuthentication/Viewcontroller/TermsViewController.swift
> [#204] fix: 약관 동의 싱글톤 버그 수정

- DrinkingGourmet.xcodeproj/project.pbxproj
- DrinkingGourmet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- DrinkingGourmet/Source/Combination/Upload/ViewController/CombinationUploadVC.swift
- DrinkingGourmet/Source/Mypage/View/MyPageView.swift
- DrinkingGourmet/Source/Mypage/ViewController/MyPageViewController.swift
- DrinkingGourmet/Source/Network/Service/MyPageService.swift
- DrinkingGourmet/Source/RecipeBook/Upload/ViewController/RecipeBookUploadViewController.swift
- DrinkingGourmet/Source/Setting/Home/View/SettingTopView.swift
- DrinkingGourmet/Source/Setting/Home/ViewController/SettingViewController.swift
- DrinkingGourmet/Source/UserAuthentication/Viewcontroller/ProfileCreationViewController.swift
- DrinkingGourmet/Source/UserAuthentication/Viewcontroller/TermsViewController.swift
resolve #208  
https://github.com/user-attachments/assets/97553792-970c-4e72-a331-88cb141ad741
> [#208] feat: 업로드 페이지 DynamicTextView 구현

- DrinkingGourmet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- DrinkingGourmet.xcodeproj/xcuserdata/hwijinjeong.xcuserdatad/xcschemes/xcschememanagement.plist
- DrinkingGourmet/Source/UserAuthentication/TokenParser.swift
> [KAN-26][refactor] 토큰 만료 판별시, exp 기반으로 판별하도록 수정

- .gitignore
- DrinkingGourmet.xcodeproj/project.pbxproj
- DrinkingGourmet.xcodeproj/xcshareddata/xcschemes/DrinkingGourmet.xcscheme
- DrinkingGourmet.xcodeproj/xcuserdata/hwijinjeong.xcuserdatad/xcschemes/xcschememanagement.plist
- DrinkingGourmet/.gitignore
> [#214][CHORE] build setting 설정

- .gitignore
- DrinkingGourmet.xcodeproj/project.pbxproj
- DrinkingGourmet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- DrinkingGourmet.xcodeproj/xcshareddata/xcschemes/DrinkingGourmet.xcscheme
- DrinkingGourmet.xcodeproj/xcuserdata/hwijinjeong.xcuserdatad/xcschemes/xcschememanagement.plist
- DrinkingGourmet/.gitignore
- DrinkingGourmet/Source/UserAuthentication/Viewcontroller/AuthenticationViewController.swift
> [#217][FIX] UserDefault에서 이메일 없을 때 -1 대신 빈 문자열로 처리

- DrinkingGourmet/Source/Combination/Upload/ViewController/CombinationUploadVC.swift
- DrinkingGourmet/Source/MainMenu/ViewController/MainMenuViewController.swift
- DrinkingGourmet/Source/RecipeBook/Upload/ViewController/RecipeBookUploadViewController.swift
> [#221] feat: 메인페이지에서 게시글로 push될 때 바텀바 숨기기

- DrinkingGourmet/Source/Combination/Upload/ViewController/CombinationUploadVC.swift
- DrinkingGourmet/Source/MainMenu/ViewController/MainMenuViewController.swift
- DrinkingGourmet/Source/RecipeBook/Upload/ViewController/RecipeBookUploadViewController.swift
> [#223] fix: 오늘의 조합 업로드 추천 받은 조합이 없을 때 aleart

- DrinkingGourmet.xcodeproj/project.pbxproj
- DrinkingGourmet/Source/Network/Auth/AuthInterceptor.swift
- DrinkingGourmet/Source/Network/Service/SignService.swift
> [#227][FIX] 토큰 재발급 요청 시 헤더 및 토큰 처리 로직 수정

- DrinkingGourmet/Source/Combination/Detail/ViewController/CombinationDetailViewController.swift
- DrinkingGourmet/Source/Combination/RemovedAlertView.swift
- DrinkingGourmet/Source/RecipeBook/Detail/ViewController/RecipeBookDetailViewController.swift
- DrinkingGourmet/Source/Recommend/RequestRecommend/View/InputIntoxicationview.swift
- DrinkingGourmet/Source/Recommend/RequestRecommend/View/RecommendLodingView.swift
- DrinkingGourmet/Source/Recommend/RequestRecommend/ViewController/InputIntoxicationViewController.swift
- DrinkingGourmet/Source/Recommend/RequestRecommend/ViewController/RecommendLodingViewController.swift
resolve #231
https://github.com/user-attachments/assets/f5caac76-e37f-4d1f-8e5f-1199f0341ca0
https://github.com/user-attachments/assets/873755e2-5a30-4016-a1d3-714a9fa336ee
https://github.com/user-attachments/assets/1fb09475-b0a4-4d16-ba38-0cd9954bdb4e
> [#231] feat: 주류추천 페이지 슬라이드바 범위, 소요시간 텍스트 label, 차단 aleart 추가

- DrinkingGourmet/Source/Network/Service/SignService.swift
- DrinkingGourmet/Source/UserAuthentication/Viewcontroller/AuthenticationViewController.swift
> 자동로그인 안되는 이슈 해결

- DrinkingGourmet/Source/MainMenu/ViewController/MainMenuViewController.swift
- DrinkingGourmet/Source/Network/DTOs/Response/RecipeResponseDTO.swift
- DrinkingGourmet/Source/Network/Models/RecipeModel.swift
- DrinkingGourmet/Source/Network/Service/SignService.swift
- DrinkingGourmet/Source/UserAuthentication/Viewcontroller/AuthenticationViewController.swift
> 레시피북 이미지 응답값에 대해 옵셔널 처리

- DrinkingGourmet/Source/Combination/Detail/ViewController/CombinationDetailViewController.swift
- DrinkingGourmet/Source/MainMenu/ViewController/MainMenuViewController.swift
- DrinkingGourmet/Source/RecipeBook/Detail/ViewController/RecipeBookDetailViewController.swift
- DrinkingGourmet/Source/WeeklyBest/ViewController/WeeklyBestViewController.swift
resolve #240 
- 게시글 상세화면 naviBar 투명
- 메인페이지 더미 광고 삭제
- 주간 베스트조합 검색창 placholder 수정
> [#240] design: 자잘한 디자인 수정

- DrinkingGourmet.xcodeproj/project.pbxproj
- DrinkingGourmet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- DrinkingGourmet/Source/MainMenu/ViewController/MainMenuViewController.swift
- DrinkingGourmet/Source/MainMenu/ViewController/RecipeBookCollectionViewCell.swift
- DrinkingGourmet/Source/MainMenu/ViewController/TodayCombiCollectionViewCell.swift
resolve #242 
resolve #243 
resolve #244
> 메인페이지 CollectionView 내부 Label UI 수정

- DrinkingGourmet/Source/Recommend/RequestRecommend/ViewController/InputIntoxicationViewController.swift
> [#246] design: 주류추천 슬라이더 페이지 nextButton 상시 활성화

- DrinkingGourmet.xcodeproj/project.pbxproj
- DrinkingGourmet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- DrinkingGourmet/PrivacyInfo.xcprivacy
> UserDefaults 접근 및 미디어 캐싱 관련하여 App Privacy 파일 추가

- DrinkingGourmet.xcodeproj/project.pbxproj
- DrinkingGourmet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- DrinkingGourmet/Info.plist
- DrinkingGourmet/PrivacyInfo.xcprivacy
> [feat] info.plist에 갤러리 접근 권한 추가
